version: "3"
services:
  jenkins:
    build:
      context: ./docker
      dockerfile: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    links:
      - verdaccio
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  verdaccio:
    build:
      context: ./docker
      dockerfile: verdaccio
    ports:
      - "4873:4873"
